### ISSUE TITLE
Unpinned/unfrozen `requirements.txt` breaks builds on Linux

### ISSUE THREAD

**Issue by wallyhall** [toradex/moses#1]
Hi,
I've spent a day trying to work through various issues building `moses` on Ubuntu.  Using 18.04 (like your gitlab build pipeline), I've hit two issues which both seem related to unpinned/unfrozen packages used downstream as dependencies of your dependencies.  (I _think_.)

Errors were immediately being thrown relating to OpenAPI and subsequently PySSL; adding the following two specific package versions to `requirements.txt` seems to have cleared up the issues (but may well break until the full list of dependency dependents is frozen?):

```
pyOpenSSL==22.0.0
openapi-spec-validator==0.3.1
```

**Comment by andreriesco** [comment]
Hello @wallyhall,
Can you try using the code available on the `dev` branch please? Because the last commit on this branch is the lock of the packages in the `requirements.txt` that should fix this building `moses` problem: https://github.com/toradex/moses/commit/da95150cd889e1b98761d3d8cbd04cb8cce274f9

**Comment by wallyhall** [comment]
I can confirm that's worked perfectly!  Thank-you for the rapid fix!

**Comment by andreriesco** [comment]
Glad to here that @wallyhall,
Also, a ZIP file containing `moses-linux` that gets updated every time a new commit is added on the `dev` branch can be downloaded here: [https://artifacts.toradex.com:443/artifactory/ideextension-moses-prod-frankfurt/moses-linux.zip](https://artifacts.toradex.com:443/artifactory/ideextension-moses-prod-frankfurt/moses-linux.zip)

**Comment by andreriesco** [comment]
Also, on the latest Early Access version(1.6.4 - released yesterday) of the Extension for Torizon, there is a command that automatically generates a GitHub Actions CI/CD pipeline that compiles the source code, builds the release container for the application, pushes this container to DockerHub and Publishes the Docker Compose file on the Torizon Platform.
For more details, including a tutorial video of the new command, please check the decumentation on the new [Continuous Integration and Continuous Delivery section](https://developer.toradex.com/torizon/working-with-torizon/application-development/visual-studio-code-extension-for-torizon/#continuous-integration-and-continuous-delivery) of the VSCode Extension for Torizon main page!!

**Comment by andreriesco** [comment]
Also, on the latest Toradex Torizon Support (Early Access) VSCode Extesion (version 1.6.4 - released yesterday), there is a command that automatically generates a GitHub Actions CI/CD pipeline that compiles the source code, builds the release container for the application, pushes this container to DockerHub and Publishes the Docker Compose file on the Torizon Platform.

For more details, including a tutorial video of the new command, please check the decumentation on the new [Continuous Integration and Continuous Delivery section](https://developer.toradex.com/torizon/working-with-torizon/application-development/visual-studio-code-extension-for-torizon/#continuous-integration-and-continuous-delivery) of the VSCode Extension for Torizon main page!!
